### PR TITLE
Fix the Unit of Work persistState() method in a sequenced call

### LINKED ISSUE #424: 🐛 Multiple persistState only works once
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

Hello!

I caught a not quite obvious situation with `peristState`. Yes, I read this:
> Entity will be queued up with fixing current state. Entity state changes after adding to the queue will be ignored.

But why?

Example with `persistState`:
```php
public function testTest1(): void
{
    /** @var EntityManagerInterface $entityManager */
    $entityManager = $this->app->get(EntityManagerInterface::class);

    $user = new User(
        id: UserId::fromInt(100),
    );

    $entityManager->persistState($user);

    $user->isSome = true;

    $entityManager->persistState($user);
    $entityManager->run();

    $this->assertDatabaseHas('users', [
        'id' => 100,
        'is_some' => 1, // fails, is_some = 0
    ]);
}
```
Example with persist:
```php
public function testTest2(): void
{
    /** @var EntityManagerInterface $entityManager */
    $entityManager = $this->app->get(EntityManagerInterface::class);

    $user = new User(
        id: UserId::fromInt(100),
    );

    $entityManager->persist($user);

    $user->isSome = true;

    $entityManager->run();

    $this->assertDatabaseHas('users', [
        'id' => 100,
        'is_some' => 1, // ok, is_some = 1
    ]);
}
```
But I can't use `persist` because #392. Maybe I don't understand something?

### Version

```shell
ORM 2.3.2
PHP 8.2
```

### PR DESCRIPTION
**Pull request by msmakouz**

### CODE REVIEW

File: src/Transaction/Pool.php [hunk 1]
```diff
@@ -337,6 +337,9 @@ private function snap(Tuple $tuple): void
             $tuple->state = $tuple->node->createState();
             $tuple->state->setData($tuple->mapper->fetchFields($entity));
         }
+        if ($forceUpdateState) {
```
Comment (roxblnfk) [inline src/Transaction/Pool.php]:
```suggestion
        elseif ($forceUpdateState) {
```

File: tests/ORM/Functional/Driver/Common/Integration/Issue424/CaseTest.php
Comment (roxblnfk) [inline tests/ORM/Functional/Driver/Common/Integration/Issue424/CaseTest.php:1]: you can remove that case because it is dublicate of testPersistStateTwiceAndChangeEntity and testPersistStateTwiceAndChangeEntityWithStoredEntity

**Review by roxblnfk — APPROVED** [review]
